/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.util.htdAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class htdItemProviderAdapterFactory extends htdAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public htdItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TArgument} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TArgumentItemProvider tArgumentItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TArgument}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTArgumentAdapter() {
		if (tArgumentItemProvider == null) {
			tArgumentItemProvider = new TArgumentItemProvider(this);
		}

		return tArgumentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TBooleanExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TBooleanExprItemProvider tBooleanExprItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TBooleanExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTBooleanExprAdapter() {
		if (tBooleanExprItemProvider == null) {
			tBooleanExprItemProvider = new TBooleanExprItemProvider(this);
		}

		return tBooleanExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDeadlineItemProvider tDeadlineItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDeadlineAdapter() {
		if (tDeadlineItemProvider == null) {
			tDeadlineItemProvider = new TDeadlineItemProvider(this);
		}

		return tDeadlineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadlineExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDeadlineExprItemProvider tDeadlineExprItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadlineExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDeadlineExprAdapter() {
		if (tDeadlineExprItemProvider == null) {
			tDeadlineExprItemProvider = new TDeadlineExprItemProvider(this);
		}

		return tDeadlineExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadlines} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDeadlinesItemProvider tDeadlinesItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDeadlines}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDeadlinesAdapter() {
		if (tDeadlinesItemProvider == null) {
			tDeadlinesItemProvider = new TDeadlinesItemProvider(this);
		}

		return tDeadlinesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDelegation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDelegationItemProvider tDelegationItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDelegation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDelegationAdapter() {
		if (tDelegationItemProvider == null) {
			tDelegationItemProvider = new TDelegationItemProvider(this);
		}

		return tDelegationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDescription} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDescriptionItemProvider tDescriptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDescription}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDescriptionAdapter() {
		if (tDescriptionItemProvider == null) {
			tDescriptionItemProvider = new TDescriptionItemProvider(this);
		}

		return tDescriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDocumentation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDocumentationItemProvider tDocumentationItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDocumentation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDocumentationAdapter() {
		if (tDocumentationItemProvider == null) {
			tDocumentationItemProvider = new TDocumentationItemProvider(this);
		}

		return tDocumentationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDurationExpr} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TDurationExprItemProvider tDurationExprItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TDurationExpr}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTDurationExprAdapter() {
		if (tDurationExprItemProvider == null) {
			tDurationExprItemProvider = new TDurationExprItemProvider(this);
		}

		return tDurationExprItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TEscalation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TEscalationItemProvider tEscalationItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TEscalation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTEscalationAdapter() {
		if (tEscalationItemProvider == null) {
			tEscalationItemProvider = new TEscalationItemProvider(this);
		}

		return tEscalationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TExpressionItemProvider tExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTExpressionAdapter() {
		if (tExpressionItemProvider == null) {
			tExpressionItemProvider = new TExpressionItemProvider(this);
		}

		return tExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensibleElements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TExtensibleElementsItemProvider tExtensibleElementsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensibleElements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTExtensibleElementsAdapter() {
		if (tExtensibleElementsItemProvider == null) {
			tExtensibleElementsItemProvider = new TExtensibleElementsItemProvider(this);
		}

		return tExtensibleElementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensibleMixedContentElements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TExtensibleMixedContentElementsItemProvider tExtensibleMixedContentElementsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensibleMixedContentElements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTExtensibleMixedContentElementsAdapter() {
		if (tExtensibleMixedContentElementsItemProvider == null) {
			tExtensibleMixedContentElementsItemProvider = new TExtensibleMixedContentElementsItemProvider(this);
		}

		return tExtensibleMixedContentElementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtension} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TExtensionItemProvider tExtensionItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtension}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTExtensionAdapter() {
		if (tExtensionItemProvider == null) {
			tExtensionItemProvider = new TExtensionItemProvider(this);
		}

		return tExtensionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TExtensionsItemProvider tExtensionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TExtensions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTExtensionsAdapter() {
		if (tExtensionsItemProvider == null) {
			tExtensionsItemProvider = new TExtensionsItemProvider(this);
		}

		return tExtensionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TFrom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TFromItemProvider tFromItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TFrom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTFromAdapter() {
		if (tFromItemProvider == null) {
			tFromItemProvider = new TFromItemProvider(this);
		}

		return tFromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TGenericHumanRole} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TGenericHumanRoleItemProvider tGenericHumanRoleItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TGenericHumanRole}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTGenericHumanRoleAdapter() {
		if (tGenericHumanRoleItemProvider == null) {
			tGenericHumanRoleItemProvider = new TGenericHumanRoleItemProvider(this);
		}

		return tGenericHumanRoleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TGrouplist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TGrouplistItemProvider tGrouplistItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TGrouplist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTGrouplistAdapter() {
		if (tGrouplistItemProvider == null) {
			tGrouplistItemProvider = new TGrouplistItemProvider(this);
		}

		return tGrouplistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.THumanInteractions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected THumanInteractionsItemProvider tHumanInteractionsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.THumanInteractions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTHumanInteractionsAdapter() {
		if (tHumanInteractionsItemProvider == null) {
			tHumanInteractionsItemProvider = new THumanInteractionsItemProvider(this);
		}

		return tHumanInteractionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TImportItemProvider tImportItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTImportAdapter() {
		if (tImportItemProvider == null) {
			tImportItemProvider = new TImportItemProvider(this);
		}

		return tImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TLiteralItemProvider tLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTLiteralAdapter() {
		if (tLiteralItemProvider == null) {
			tLiteralItemProvider = new TLiteralItemProvider(this);
		}

		return tLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLocalNotification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TLocalNotificationItemProvider tLocalNotificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLocalNotification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTLocalNotificationAdapter() {
		if (tLocalNotificationItemProvider == null) {
			tLocalNotificationItemProvider = new TLocalNotificationItemProvider(this);
		}

		return tLocalNotificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLogicalPeopleGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TLogicalPeopleGroupItemProvider tLogicalPeopleGroupItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLogicalPeopleGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTLogicalPeopleGroupAdapter() {
		if (tLogicalPeopleGroupItemProvider == null) {
			tLogicalPeopleGroupItemProvider = new TLogicalPeopleGroupItemProvider(this);
		}

		return tLogicalPeopleGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLogicalPeopleGroups} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TLogicalPeopleGroupsItemProvider tLogicalPeopleGroupsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TLogicalPeopleGroups}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTLogicalPeopleGroupsAdapter() {
		if (tLogicalPeopleGroupsItemProvider == null) {
			tLogicalPeopleGroupsItemProvider = new TLogicalPeopleGroupsItemProvider(this);
		}

		return tLogicalPeopleGroupsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TNotificationItemProvider tNotificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTNotificationAdapter() {
		if (tNotificationItemProvider == null) {
			tNotificationItemProvider = new TNotificationItemProvider(this);
		}

		return tNotificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotificationInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TNotificationInterfaceItemProvider tNotificationInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotificationInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTNotificationInterfaceAdapter() {
		if (tNotificationInterfaceItemProvider == null) {
			tNotificationInterfaceItemProvider = new TNotificationInterfaceItemProvider(this);
		}

		return tNotificationInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotifications} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TNotificationsItemProvider tNotificationsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TNotifications}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTNotificationsAdapter() {
		if (tNotificationsItemProvider == null) {
			tNotificationsItemProvider = new TNotificationsItemProvider(this);
		}

		return tNotificationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TOrganizationalEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TOrganizationalEntityItemProvider tOrganizationalEntityItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TOrganizationalEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTOrganizationalEntityAdapter() {
		if (tOrganizationalEntityItemProvider == null) {
			tOrganizationalEntityItemProvider = new TOrganizationalEntityItemProvider(this);
		}

		return tOrganizationalEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TParameterItemProvider tParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTParameterAdapter() {
		if (tParameterItemProvider == null) {
			tParameterItemProvider = new TParameterItemProvider(this);
		}

		return tParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPeopleAssignments} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TPeopleAssignmentsItemProvider tPeopleAssignmentsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPeopleAssignments}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTPeopleAssignmentsAdapter() {
		if (tPeopleAssignmentsItemProvider == null) {
			tPeopleAssignmentsItemProvider = new TPeopleAssignmentsItemProvider(this);
		}

		return tPeopleAssignmentsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationElements} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TPresentationElementsItemProvider tPresentationElementsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationElements}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTPresentationElementsAdapter() {
		if (tPresentationElementsItemProvider == null) {
			tPresentationElementsItemProvider = new TPresentationElementsItemProvider(this);
		}

		return tPresentationElementsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TPresentationParameterItemProvider tPresentationParameterItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTPresentationParameterAdapter() {
		if (tPresentationParameterItemProvider == null) {
			tPresentationParameterItemProvider = new TPresentationParameterItemProvider(this);
		}

		return tPresentationParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationParameters} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TPresentationParametersItemProvider tPresentationParametersItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPresentationParameters}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTPresentationParametersAdapter() {
		if (tPresentationParametersItemProvider == null) {
			tPresentationParametersItemProvider = new TPresentationParametersItemProvider(this);
		}

		return tPresentationParametersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPriority} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TPriorityItemProvider tPriorityItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TPriority}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTPriorityAdapter() {
		if (tPriorityItemProvider == null) {
			tPriorityItemProvider = new TPriorityItemProvider(this);
		}

		return tPriorityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TQuery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TQueryItemProvider tQueryItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TQuery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTQueryAdapter() {
		if (tQueryItemProvider == null) {
			tQueryItemProvider = new TQueryItemProvider(this);
		}

		return tQueryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TReassignment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TReassignmentItemProvider tReassignmentItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TReassignment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTReassignmentAdapter() {
		if (tReassignmentItemProvider == null) {
			tReassignmentItemProvider = new TReassignmentItemProvider(this);
		}

		return tReassignmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TRendering} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TRenderingItemProvider tRenderingItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TRendering}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTRenderingAdapter() {
		if (tRenderingItemProvider == null) {
			tRenderingItemProvider = new TRenderingItemProvider(this);
		}

		return tRenderingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TRenderings} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TRenderingsItemProvider tRenderingsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TRenderings}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTRenderingsAdapter() {
		if (tRenderingsItemProvider == null) {
			tRenderingsItemProvider = new TRenderingsItemProvider(this);
		}

		return tRenderingsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TTaskItemProvider tTaskItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTTaskAdapter() {
		if (tTaskItemProvider == null) {
			tTaskItemProvider = new TTaskItemProvider(this);
		}

		return tTaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTaskInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TTaskInterfaceItemProvider tTaskInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTaskInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTTaskInterfaceAdapter() {
		if (tTaskInterfaceItemProvider == null) {
			tTaskInterfaceItemProvider = new TTaskInterfaceItemProvider(this);
		}

		return tTaskInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTasks} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TTasksItemProvider tTasksItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TTasks}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTTasksAdapter() {
		if (tTasksItemProvider == null) {
			tTasksItemProvider = new TTasksItemProvider(this);
		}

		return tTasksItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TTextItemProvider tTextItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTTextAdapter() {
		if (tTextItemProvider == null) {
			tTextItemProvider = new TTextItemProvider(this);
		}

		return tTextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TToPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TToPartItemProvider tToPartItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TToPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTToPartAdapter() {
		if (tToPartItemProvider == null) {
			tToPartItemProvider = new TToPartItemProvider(this);
		}

		return tToPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TToParts} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TToPartsItemProvider tToPartsItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TToParts}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTToPartsAdapter() {
		if (tToPartsItemProvider == null) {
			tToPartsItemProvider = new TToPartsItemProvider(this);
		}

		return tToPartsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TUserlist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TUserlistItemProvider tUserlistItemProvider;

	/**
	 * This creates an adapter for a {@link org.open.oasis.docs.ns.bpel4people.ws.humantask.ht.TUserlist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTUserlistAdapter() {
		if (tUserlistItemProvider == null) {
			tUserlistItemProvider = new TUserlistItemProvider(this);
		}

		return tUserlistItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (documentRootItemProvider != null) documentRootItemProvider.dispose();
		if (tArgumentItemProvider != null) tArgumentItemProvider.dispose();
		if (tBooleanExprItemProvider != null) tBooleanExprItemProvider.dispose();
		if (tDeadlineItemProvider != null) tDeadlineItemProvider.dispose();
		if (tDeadlineExprItemProvider != null) tDeadlineExprItemProvider.dispose();
		if (tDeadlinesItemProvider != null) tDeadlinesItemProvider.dispose();
		if (tDelegationItemProvider != null) tDelegationItemProvider.dispose();
		if (tDescriptionItemProvider != null) tDescriptionItemProvider.dispose();
		if (tDocumentationItemProvider != null) tDocumentationItemProvider.dispose();
		if (tDurationExprItemProvider != null) tDurationExprItemProvider.dispose();
		if (tEscalationItemProvider != null) tEscalationItemProvider.dispose();
		if (tExpressionItemProvider != null) tExpressionItemProvider.dispose();
		if (tExtensibleElementsItemProvider != null) tExtensibleElementsItemProvider.dispose();
		if (tExtensibleMixedContentElementsItemProvider != null) tExtensibleMixedContentElementsItemProvider.dispose();
		if (tExtensionItemProvider != null) tExtensionItemProvider.dispose();
		if (tExtensionsItemProvider != null) tExtensionsItemProvider.dispose();
		if (tFromItemProvider != null) tFromItemProvider.dispose();
		if (tGenericHumanRoleItemProvider != null) tGenericHumanRoleItemProvider.dispose();
		if (tGrouplistItemProvider != null) tGrouplistItemProvider.dispose();
		if (tHumanInteractionsItemProvider != null) tHumanInteractionsItemProvider.dispose();
		if (tImportItemProvider != null) tImportItemProvider.dispose();
		if (tLiteralItemProvider != null) tLiteralItemProvider.dispose();
		if (tLocalNotificationItemProvider != null) tLocalNotificationItemProvider.dispose();
		if (tLogicalPeopleGroupItemProvider != null) tLogicalPeopleGroupItemProvider.dispose();
		if (tLogicalPeopleGroupsItemProvider != null) tLogicalPeopleGroupsItemProvider.dispose();
		if (tNotificationItemProvider != null) tNotificationItemProvider.dispose();
		if (tNotificationInterfaceItemProvider != null) tNotificationInterfaceItemProvider.dispose();
		if (tNotificationsItemProvider != null) tNotificationsItemProvider.dispose();
		if (tOrganizationalEntityItemProvider != null) tOrganizationalEntityItemProvider.dispose();
		if (tParameterItemProvider != null) tParameterItemProvider.dispose();
		if (tPeopleAssignmentsItemProvider != null) tPeopleAssignmentsItemProvider.dispose();
		if (tPresentationElementsItemProvider != null) tPresentationElementsItemProvider.dispose();
		if (tPresentationParameterItemProvider != null) tPresentationParameterItemProvider.dispose();
		if (tPresentationParametersItemProvider != null) tPresentationParametersItemProvider.dispose();
		if (tPriorityItemProvider != null) tPriorityItemProvider.dispose();
		if (tQueryItemProvider != null) tQueryItemProvider.dispose();
		if (tReassignmentItemProvider != null) tReassignmentItemProvider.dispose();
		if (tRenderingItemProvider != null) tRenderingItemProvider.dispose();
		if (tRenderingsItemProvider != null) tRenderingsItemProvider.dispose();
		if (tTaskItemProvider != null) tTaskItemProvider.dispose();
		if (tTaskInterfaceItemProvider != null) tTaskInterfaceItemProvider.dispose();
		if (tTasksItemProvider != null) tTasksItemProvider.dispose();
		if (tTextItemProvider != null) tTextItemProvider.dispose();
		if (tToPartItemProvider != null) tToPartItemProvider.dispose();
		if (tToPartsItemProvider != null) tToPartsItemProvider.dispose();
		if (tUserlistItemProvider != null) tUserlistItemProvider.dispose();
	}

}
